### PR TITLE
Solves issue #26

### PR DESCRIPTION
**Pull request by mgrundkoetter**

### CODE REVIEW

**Comment by DavidBruchmann** [comment]
Thanks a lot, give us the following weekend for a review of all issues you solve(d) now.

**Comment by schams-net** [comment]
Sorry - this is maybe a really stupid question - but can't we use a much simpler solution such as:
```
public function render($condition) {
  if ($condition) {
    return $this->renderThenChild();
  } else {
    return $this->renderElseChild();
  }
}
```

**Comment by DavidBruchmann** [comment]
@mgrundkoetter I tend to agree to @schams-net, that would be more common, I never knew the verdict function before looking up now. You've a reason for having taken the verdict function in disadvantage of render and renderStatic?

**Comment by mgrundkoetter** [comment]
Yes, thats the recommended way of using the viewhelper now. It is static, which has better performance because of caching. Also: the whole logic for then/else is handled in the parent class and the derived classes only need to overwrite the `verdict` method. Before, it was `evaluateCondition`, but this is now deprecated, see https://github.com/TYPO3/Fluid/pull/393 So using the "old" stuff is not a good solution!

**Comment by schams-net** [comment]
I did some research and @mgrundkoetter is absolutely right. The proposed solution is state-of-the-art and in fact the recommended way to build Condition-ViewHelpers now. Many thanks for your insight!

The code looks perfectly fine, but I have not tested the updated ViewHelper in `EXT:typo3_forum` and/or TYPO3 v8 though.

PS: I made a note to take this into account for the 3rd edition of the [TYPO3 Extbase book](https://extbase-book.org) :-)

**Pull request merged**
